export type { PatchMode, PatchParams, GitCommand, PatchSummaryItem, PatchRule, FileSelection } from './core/patch-types.js'
export { sanitizeFileSegment } from './core/sanitize-file-segment.js'
export { ensurePatchExtension } from './core/ensure-patch-extension.js'
export { buildStagedFileName } from './core/build-staged-file-name.js'
export { buildBranchCompareFileName } from './core/build-branch-compare-file-name.js'
export { buildTagCompareFileName } from './core/build-tag-compare-file-name.js'
export { buildStagedGitCommand } from './core/build-staged-git-command.js'
export { buildBranchCompareGitCommand } from './core/build-branch-compare-git-command.js'
export { buildTagCompareGitCommand } from './core/build-tag-compare-git-command.js'
export { validateBranchCompareInput } from './core/validate-branch-compare-input.js'
export { validateTagCompareInput } from './core/validate-tag-compare-input.js'
export { buildStagedSummary, buildBranchCompareSummary, buildTagCompareSummary } from './core/build-summary.js'
export { patchRules, findPatchRule } from './config/patch-rules.js'
